#pandas
- Dataframe
- Dataframe functions and properties
    - .head(no_of_rows_you_need)
    - .tail(no_of_rows_you_need)
    - .columns # property dont need parenthesis
    - .to_csv("file_name.csv")
    - .read_csv("file_name.csv")
    - .drop(columns=["column_name"])  # not inplace
    - .describe()
    - .iloc[row_index, column_index]
    - columns.get_loc("column_name") # to get index of location
    - .iloc[row_index, column_index] # i stands for integer based its more compatible with integer idx. Especially when slicing parts of df
    - .sort_values(by="column_name", ascending=False) # sort by column
    - .values # property
    - .shape # property

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame()

In [3]:
user_data = {
    "MarksA": np.random.randint(1,100,5),
    "MarksB": np.random.randint(50,100,5),
    "MarksC": np.random.randint(1,100,5)
}
user_data

{'MarksA': array([76, 52, 27,  9, 49]),
 'MarksB': array([57, 95, 50, 74, 81]),
 'MarksC': array([ 6, 69, 10, 64, 99])}

In [4]:
df = pd.DataFrame(user_data)

In [5]:
print(df)

   MarksA  MarksB  MarksC
0      76      57       6
1      52      95      69
2      27      50      10
3       9      74      64
4      49      81      99


In [6]:
df.head(5)

MarksA  MarksB  MarksC
0      76      57       6
1      52      95      69
2      27      50      10
3       9      74      64
4      49      81      99

In [7]:
df.columns

Index(['MarksA', 'MarksB', 'MarksC'], dtype='object')

In [8]:
df.to_csv("delete.csv",index=False)

In [9]:
loaded_data = pd.read_csv("delete.csv")

In [10]:
loaded_data = loaded_data.drop(columns=["MarksA"])
loaded_data

MarksB  MarksC
0      57       6
1      95      69
2      50      10
3      74      64
4      81      99

In [11]:
del loaded_data

## video 2

In [12]:
df.describe()

MarksA     MarksB     MarksC
count   5.000000   5.000000   5.000000
mean   42.600000  71.400000  49.600000
std    25.579288  18.174157  40.290197
min     9.000000  50.000000   6.000000
25%    27.000000  57.000000  10.000000
50%    49.000000  74.000000  64.000000
75%    52.000000  81.000000  69.000000
max    76.000000  95.000000  99.000000

In [13]:
print(df.head())


   MarksA  MarksB  MarksC
0      76      57       6
1      52      95      69
2      27      50      10
3       9      74      64
4      49      81      99


In [14]:
df.iloc[3]

MarksA     9
MarksB    74
MarksC    64
Name: 3, dtype: int64

In [15]:
print(df.iloc[3]["MarksA"])
print("\n")
print(df.iloc[3][0])
print("\n")
print(df.iloc[3,[1,2]]) # cant use names f multiple columns we will have to use loc to use MarksA,MarksB in place of 1,2
print("\n")
print(df.iloc[1:3,[1,2]])

9


9


MarksB    74
MarksC    64
Name: 3, dtype: int64


   MarksB  MarksC
1      95      69
2      50      10


In [16]:
idx = df.columns.get_loc("MarksA")
print(df.iloc[3,idx])

9


In [17]:
df.sort_values(by=["MarksA","MarksC"],ascending=True) # prioritize by A then C

MarksA  MarksB  MarksC
3       9      74      64
2      27      50      10
4      49      81      99
1      52      95      69
0      76      57       6

In [18]:
#getting numpy from df

a = df.values
print(type(a))
print(a)

<class 'numpy.ndarray'>
[[76 57  6]
 [52 95 69]
 [27 50 10]
 [ 9 74 64]
 [49 81 99]]


In [19]:
df.shape

(5, 3)

In [20]:
df_new= pd.DataFrame(a,columns=["MarksA","MarksB","MarksC"])

In [21]:
df_new

MarksA  MarksB  MarksC
0      76      57       6
1      52      95      69
2      27      50      10
3       9      74      64
4      49      81      99